# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GAuthPayload.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GAuthPayload.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12GAuthPayload.proto\"\xf0\x02\n\x0cGAuthPayload\x12&\n\x07payload\x18\x01 \x03(\x0b\x32\x15.GAuthPayload.Payload\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\x1a\xa3\x01\n\x07Payload\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12$\n\talgorithm\x18\x04 \x01(\x0e\x32\x11.GAuthPayload.Alg\x12\x0e\n\x06\x64igits\x18\x05 \x01(\x05\x12#\n\x04type\x18\x06 \x01(\x0e\x32\x15.GAuthPayload.OtpType\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x03\"\x1a\n\x03\x41lg\x12\t\n\x05\x45RROR\x10\x00\x12\x08\n\x04SHA1\x10\x01\"*\n\x07OtpType\x12\x0b\n\x07INVALID\x10\x00\x12\x08\n\x04HOTP\x10\x01\x12\x08\n\x04TOTP\x10\x02\x62\x06proto3'
)



_GAUTHPAYLOAD_ALG = _descriptor.EnumDescriptor(
  name='Alg',
  full_name='GAuthPayload.Alg',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHA1', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=321,
  serialized_end=347,
)
_sym_db.RegisterEnumDescriptor(_GAUTHPAYLOAD_ALG)

_GAUTHPAYLOAD_OTPTYPE = _descriptor.EnumDescriptor(
  name='OtpType',
  full_name='GAuthPayload.OtpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOTP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOTP', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=349,
  serialized_end=391,
)
_sym_db.RegisterEnumDescriptor(_GAUTHPAYLOAD_OTPTYPE)


_GAUTHPAYLOAD_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='GAuthPayload.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secret', full_name='GAuthPayload.Payload.secret', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='GAuthPayload.Payload.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issuer', full_name='GAuthPayload.Payload.issuer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='GAuthPayload.Payload.algorithm', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digits', full_name='GAuthPayload.Payload.digits', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='GAuthPayload.Payload.type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='GAuthPayload.Payload.counter', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=319,
)

_GAUTHPAYLOAD = _descriptor.Descriptor(
  name='GAuthPayload',
  full_name='GAuthPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='GAuthPayload.payload', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='GAuthPayload.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='GAuthPayload.batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_index', full_name='GAuthPayload.batch_index', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='GAuthPayload.batch_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GAUTHPAYLOAD_PAYLOAD, ],
  enum_types=[
    _GAUTHPAYLOAD_ALG,
    _GAUTHPAYLOAD_OTPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=391,
)

_GAUTHPAYLOAD_PAYLOAD.fields_by_name['algorithm'].enum_type = _GAUTHPAYLOAD_ALG
_GAUTHPAYLOAD_PAYLOAD.fields_by_name['type'].enum_type = _GAUTHPAYLOAD_OTPTYPE
_GAUTHPAYLOAD_PAYLOAD.containing_type = _GAUTHPAYLOAD
_GAUTHPAYLOAD.fields_by_name['payload'].message_type = _GAUTHPAYLOAD_PAYLOAD
_GAUTHPAYLOAD_ALG.containing_type = _GAUTHPAYLOAD
_GAUTHPAYLOAD_OTPTYPE.containing_type = _GAUTHPAYLOAD
DESCRIPTOR.message_types_by_name['GAuthPayload'] = _GAUTHPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GAuthPayload = _reflection.GeneratedProtocolMessageType('GAuthPayload', (_message.Message,), {

  'Payload' : _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
    'DESCRIPTOR' : _GAUTHPAYLOAD_PAYLOAD,
    '__module__' : 'GAuthPayload_pb2'
    # @@protoc_insertion_point(class_scope:GAuthPayload.Payload)
    })
  ,
  'DESCRIPTOR' : _GAUTHPAYLOAD,
  '__module__' : 'GAuthPayload_pb2'
  # @@protoc_insertion_point(class_scope:GAuthPayload)
  })
_sym_db.RegisterMessage(GAuthPayload)
_sym_db.RegisterMessage(GAuthPayload.Payload)


# @@protoc_insertion_point(module_scope)
